### PR TITLE
Update API, add new shortcode, and increase performance.

### PR DESCRIPTION
**Pull request by WPprodigy**
Will write more about the changes once 3.0 is ready for release.

### CODE REVIEW

**Comment by danicasati** [comment]
Can't wait for test this release?
Are you planning to update plugin to Wordpress official repository?

**Comment by WPprodigy** [comment]
> Can't wait for test this release?

You can try it out now, but a lot's broken with not much backwards compatibility atm. So you might want to wait till I tag the release, and have the readme updated :)

> Are you planning to update plugin to Wordpress official repository?

I've thought about it, but not too sure yet. This release will hopefully make it a lot more useful so perhaps.

**Comment by danicasati** [comment]
Good news!
I'll wait for final release to test it

If you upload into Wordpress repository, updates could be more easier for any kind of user.

**Comment by WPprodigy** [comment]
Okay @danicasati, readme is up to date. You can find the new features mentioned there, and you can download the release here: https://github.com/WPprodigy/woocommerce-external-product-embed/releases

**Pull request merged**
